# Generated by Django 3.1.4 on 2023-04-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20230428_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='age',
        ),
    ]
