# Generated by Django 3.1.4 on 2023-04-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_remove_prospect_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
