# Generated by Django 3.1.4 on 2023-04-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_prospect_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prospect',
            new_name='Lead',
        ),
    ]
