# Generated by Django 3.1.4 on 2023-04-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_auto_20230428_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': 'Prospect', 'verbose_name_plural': 'Prospect'},
        ),
    ]
