# Generated by Django 3.1.4 on 2023-04-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_auto_20230428_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
    ]
