# Generated by Django 3.1.4 on 2023-04-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_auto_20230428_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='age',
        ),
    ]
