# Generated by Django 3.1.4 on 2023-04-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_remove_lead_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact',
            field=models.CharField(default='', max_length=20),
        ),
    ]
